// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'app', kind: "module", path: './app.html', attributes: []},
{name: 'app.getFromDubJson', kind: "functiondeclaration", path: './app/getFromDubJson.html', attributes: ["auto"]},
{name: 'app.getFromDubJsonFromPackageDir', kind: "functiondeclaration", path: './app/getFromDubJsonFromPackageDir.html', attributes: ["auto"]},
{name: 'app.getFromDubSdl', kind: "functiondeclaration", path: './app/getFromDubSdl.html', attributes: ["auto"]},
{name: 'app.getFromDubSdlFromPackageDir', kind: "functiondeclaration", path: './app/getFromDubSdlFromPackageDir.html', attributes: []},
{name: 'app.getFromGit', kind: "functiondeclaration", path: './app/getFromGit.html', attributes: []},
{name: 'app.getVersion', kind: "functiondeclaration", path: './app/getVersion.html', attributes: []},
{name: 'app.main', kind: "functiondeclaration", path: './app/main.html', attributes: []},
{name: 'app.packageDir', kind: "functiondeclaration", path: './app/packageDir.html', attributes: ["auto", "safe"]},
{name: 'app.writeContent', kind: "functiondeclaration", path: './app/writeContent.html', attributes: []},
];
