// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'app', kind: "module", path: './app.html', attributes: []},
{name: 'app.getFromDubSdl', kind: "functiondeclaration", path: './app/getFromDubSdl.html', attributes: ["auto", "safe"]},
{name: 'app.getVersion', kind: "functiondeclaration", path: './app/getVersion.html', attributes: []},
{name: 'app.main', kind: "functiondeclaration", path: './app/main.html', attributes: []},
{name: 'app.writeContent', kind: "functiondeclaration", path: './app/writeContent.html', attributes: []},
];
